name: Script Test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - name: Exec Script
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
